[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060
[1000]
type=endpoint
context=default
disallow=all
allow=ulaw
auth=1000-auth
aors=1000-aor
direct_media=no
[1000-auth]
type=auth
auth_type=userpass
username=1000
password=1234
[1000-aor]
type=aor
max_contacts=1
[1000-identify]
type=identify
endpoint=1000
match=0.0.0.0/0

